apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tsprojet
spec:
  destination:
    namespace: tsprojet
    server: https://kubernetes.default.svc:443
  source:
    path: helm
    repoURL: https://github.com/benoit-planche/tsprojet
    targetRevision: HEAD
  sources: []
  project: default
